/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofinal.frontend;

import java.util.ArrayList;
import java.util.List;
import projetofinal.backend.Disciplina;
import projetofinal.backend.Professor;

/**
 *
 * @author rolemberg
 */
public class AlocarProfessor extends javax.swing.JFrame {

    /**
     * Creates new form AlocarProfessor
     */
      
    static List<Disciplina> disciplinas;
    static List<Professor> professores;
    
    static List<Disciplina>  instanciaDisc;
    static List<Professor> instanciaProf;
    
    public AlocarProfessor(List<Disciplina> discParam,List<Professor> profParam,List<Disciplina> discInst ,List<Professor> profInst) {
        initComponents();
        disciplinas=discParam;
        professores=profParam;
        instanciaDisc=discInst;
        instanciaProf=profInst;
        
        this.setVisible(true);
        cb1.setVisible(true);
        cb2.setVisible(false);
        cb3.setVisible(false);
        cb4.setVisible(false);
        cb5.setVisible(false);
        cb6.setVisible(false);
        cb7.setVisible(false);
        cb8.setVisible(false);
        cb9.setVisible(false);
        cb10.setVisible(false);
        
        int n =profParam.size();
        for (int i = 0; i < n; i++) {
            String temp= "Matricula:"+profParam.get(i).getMatricula()+" Nome:"+profParam.get(i).getNome()+" Preferencias:";
            
            
            int j=profParam.get(i).getPreferencias().size();
            for (int k = 0; k < j; k++) {
                temp=temp + profParam.get(i).getPreferencias().get(k).getCodigo()+"-";
            }
            temp=temp+profParam.get(i).getRestricaoString();
            cb1.addItem(temp);
            cb2.addItem(temp);
            cb3.addItem(temp);
            cb4.addItem(temp);
            cb5.addItem(temp);
            cb6.addItem(temp);
            cb7.addItem(temp);
            cb8.addItem(temp);
            cb9.addItem(temp);
            cb10.addItem(temp);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        qtdeProf = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        cb2 = new javax.swing.JComboBox<>();
        cb3 = new javax.swing.JComboBox<>();
        cb4 = new javax.swing.JComboBox<>();
        cb5 = new javax.swing.JComboBox<>();
        cb6 = new javax.swing.JComboBox<>();
        cb7 = new javax.swing.JComboBox<>();
        cb8 = new javax.swing.JComboBox<>();
        cb9 = new javax.swing.JComboBox<>();
        cb10 = new javax.swing.JComboBox<>();
        btnVoltarAloc = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        qtdeProf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        qtdeProf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                qtdeProfItemStateChanged(evt);
            }
        });
        qtdeProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdeProfActionPerformed(evt);
            }
        });
        jPanel1.add(qtdeProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 99, 70, 32));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Alocar Professor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 32, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setText("Quantidade:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 100, -1, -1));

        jPanel1.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 153, 638, 40));

        jPanel1.add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 205, 638, 35));

        jPanel1.add(cb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 252, 638, 35));

        jPanel1.add(cb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 299, 638, 35));

        jPanel1.add(cb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 352, 638, 35));

        jPanel1.add(cb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 399, 638, 35));

        jPanel1.add(cb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 440, 638, 35));

        jPanel1.add(cb8, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 481, 638, 35));

        jPanel1.add(cb9, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 526, 638, 35));

        jPanel1.add(cb10, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 573, 638, 35));

        btnVoltarAloc.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        btnVoltarAloc.setText("Voltar");
        btnVoltarAloc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarAlocActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltarAloc, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 164, 46));

        btnAdd.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 164, 43));

        jLabel3.setText("Observacao: Nao sera checado se um professor sera igual ao outro,\n\n");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, -1));

        jLabel4.setText("Caso isso ocorra, nao poderemos garantir a integridade do resultado!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qtdeProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdeProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtdeProfActionPerformed

    private void btnVoltarAlocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarAlocActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new InstanciarProblema(disciplinas,professores,instanciaDisc,instanciaProf).setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnVoltarAlocActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        switch(qtdeProf.getSelectedIndex()){
            case 0:
                
                instanciaProf= new ArrayList<Professor>();
                instanciaProf.add(professores.get(cb1.getSelectedIndex()));
                this.dispose();
                new InstanciarProblema(disciplinas,professores,instanciaDisc,instanciaProf).setLocationRelativeTo(null);
                
                break;
            case 1:
                instanciaProf= new ArrayList<Professor>();
                instanciaProf.add(professores.get(cb1.getSelectedIndex()));
                instanciaProf.add(professores.get(cb2.getSelectedIndex()));
                this.dispose();
                new InstanciarProblema(disciplinas,professores,instanciaDisc,instanciaProf).setLocationRelativeTo(null);
                break;
            case 2:
                instanciaProf= new ArrayList<Professor>();
                instanciaProf.add(professores.get(cb1.getSelectedIndex()));
                instanciaProf.add(professores.get(cb2.getSelectedIndex()));
                instanciaProf.add(professores.get(cb3.getSelectedIndex()));
                this.dispose();
                new InstanciarProblema(disciplinas,professores,instanciaDisc,instanciaProf).setLocationRelativeTo(null);
                break;
            case 3:
                instanciaProf= new ArrayList<Professor>();
                instanciaProf.add(professores.get(cb1.getSelectedIndex()));
                instanciaProf.add(professores.get(cb2.getSelectedIndex()));
                instanciaProf.add(professores.get(cb3.getSelectedIndex()));
                instanciaProf.add(professores.get(cb4.getSelectedIndex()));
                this.dispose();
                new InstanciarProblema(disciplinas,professores,instanciaDisc,instanciaProf).setLocationRelativeTo(null);
                break;
            case 4:
                instanciaProf= new ArrayList<Professor>();
                instanciaProf.add(professores.get(cb1.getSelectedIndex()));
                instanciaProf.add(professores.get(cb2.getSelectedIndex()));
                instanciaProf.add(professores.get(cb3.getSelectedIndex()));
                instanciaProf.add(professores.get(cb4.getSelectedIndex()));
                instanciaProf.add(professores.get(cb5.getSelectedIndex()));
                this.dispose();
                new InstanciarProblema(disciplinas,professores,instanciaDisc,instanciaProf).setLocationRelativeTo(null);
                break;
            case 5:
                instanciaProf= new ArrayList<Professor>();
                instanciaProf.add(professores.get(cb1.getSelectedIndex()));
                instanciaProf.add(professores.get(cb2.getSelectedIndex()));
                instanciaProf.add(professores.get(cb3.getSelectedIndex()));
                instanciaProf.add(professores.get(cb4.getSelectedIndex()));
                instanciaProf.add(professores.get(cb5.getSelectedIndex()));
                instanciaProf.add(professores.get(cb6.getSelectedIndex()));
                this.dispose();
                new InstanciarProblema(disciplinas,professores,instanciaDisc,instanciaProf).setLocationRelativeTo(null);
                break;
                
            case 6:
                instanciaProf= new ArrayList<Professor>();
                instanciaProf.add(professores.get(cb1.getSelectedIndex()));
                instanciaProf.add(professores.get(cb2.getSelectedIndex()));
                instanciaProf.add(professores.get(cb3.getSelectedIndex()));
                instanciaProf.add(professores.get(cb4.getSelectedIndex()));
                instanciaProf.add(professores.get(cb5.getSelectedIndex()));
                instanciaProf.add(professores.get(cb6.getSelectedIndex()));
                instanciaProf.add(professores.get(cb7.getSelectedIndex()));
                this.dispose();
                new InstanciarProblema(disciplinas,professores,instanciaDisc,instanciaProf).setLocationRelativeTo(null);
                break;
            case 7:
                instanciaProf= new ArrayList<Professor>();
                instanciaProf.add(professores.get(cb1.getSelectedIndex()));
                instanciaProf.add(professores.get(cb2.getSelectedIndex()));
                instanciaProf.add(professores.get(cb3.getSelectedIndex()));
                instanciaProf.add(professores.get(cb4.getSelectedIndex()));
                instanciaProf.add(professores.get(cb5.getSelectedIndex()));
                instanciaProf.add(professores.get(cb6.getSelectedIndex()));
                instanciaProf.add(professores.get(cb7.getSelectedIndex()));
                instanciaProf.add(professores.get(cb8.getSelectedIndex()));
                this.dispose();
                new InstanciarProblema(disciplinas,professores,instanciaDisc,instanciaProf).setLocationRelativeTo(null);
                break;
             case 8:
                instanciaProf= new ArrayList<Professor>();
                instanciaProf.add(professores.get(cb1.getSelectedIndex()));
                instanciaProf.add(professores.get(cb2.getSelectedIndex()));
                instanciaProf.add(professores.get(cb3.getSelectedIndex()));
                instanciaProf.add(professores.get(cb4.getSelectedIndex()));
                instanciaProf.add(professores.get(cb5.getSelectedIndex()));
                instanciaProf.add(professores.get(cb6.getSelectedIndex()));
                instanciaProf.add(professores.get(cb7.getSelectedIndex()));
                instanciaProf.add(professores.get(cb8.getSelectedIndex()));
                instanciaProf.add(professores.get(cb9.getSelectedIndex()));
                this.dispose();
                new InstanciarProblema(disciplinas,professores,instanciaDisc,instanciaProf).setLocationRelativeTo(null);
                break;
            case 9:
                instanciaProf= new ArrayList<Professor>();
                instanciaProf.add(professores.get(cb1.getSelectedIndex()));
                instanciaProf.add(professores.get(cb2.getSelectedIndex()));
                instanciaProf.add(professores.get(cb3.getSelectedIndex()));
                instanciaProf.add(professores.get(cb4.getSelectedIndex()));
                instanciaProf.add(professores.get(cb5.getSelectedIndex()));
                instanciaProf.add(professores.get(cb6.getSelectedIndex()));
                instanciaProf.add(professores.get(cb7.getSelectedIndex()));
                instanciaProf.add(professores.get(cb8.getSelectedIndex()));
                instanciaProf.add(professores.get(cb9.getSelectedIndex()));
                instanciaProf.add(professores.get(cb10.getSelectedIndex()));
                this.dispose();
                new InstanciarProblema(disciplinas,professores,instanciaDisc,instanciaProf).setLocationRelativeTo(null);
                break;
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void qtdeProfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_qtdeProfItemStateChanged
        // TODO add your handling code here:
        switch(qtdeProf.getSelectedIndex()){
            case 0:
                cb1.setVisible(true);
                cb2.setVisible(false);
                cb3.setVisible(false);
                cb4.setVisible(false);
                cb5.setVisible(false);
                cb6.setVisible(false);
                cb7.setVisible(false);
                cb8.setVisible(false);
                cb9.setVisible(false);
                cb10.setVisible(false);
                break;
            case 1:
                cb1.setVisible(true);
                cb2.setVisible(true);
                cb3.setVisible(false);
                cb4.setVisible(false);
                cb5.setVisible(false);
                cb6.setVisible(false);
                cb7.setVisible(false);
                cb8.setVisible(false);
                cb9.setVisible(false);
                cb10.setVisible(false);
                break;
            case 2:
                cb1.setVisible(true);
                cb2.setVisible(true);
                cb3.setVisible(true);
                cb4.setVisible(false);
                cb5.setVisible(false);
                cb6.setVisible(false);
                cb7.setVisible(false);
                cb8.setVisible(false);
                cb9.setVisible(false);
                cb10.setVisible(false);
                break;
            case 3:
                cb1.setVisible(true);
                cb2.setVisible(true);
                cb3.setVisible(true);
                cb4.setVisible(true);
                cb5.setVisible(false);
                cb6.setVisible(false);
                cb7.setVisible(false);
                cb8.setVisible(false);
                cb9.setVisible(false);
                cb10.setVisible(false);
                break;
            case 4:
                cb1.setVisible(true);
                cb2.setVisible(true);
                cb3.setVisible(true);
                cb4.setVisible(true);
                cb5.setVisible(true);
                cb6.setVisible(false);
                cb7.setVisible(false);
                cb8.setVisible(false);
                cb9.setVisible(false);
                cb10.setVisible(false);
                break;   
            case 5:
                cb1.setVisible(true);
                cb2.setVisible(true);
                cb3.setVisible(true);
                cb4.setVisible(true);
                cb5.setVisible(true);
                cb6.setVisible(true);
                cb7.setVisible(false);
                cb8.setVisible(false);
                cb9.setVisible(false);
                cb10.setVisible(false);
                break;
                
            case 6:
                cb1.setVisible(true);
                cb2.setVisible(true);
                cb3.setVisible(true);
                cb4.setVisible(true);
                cb5.setVisible(true);
                cb6.setVisible(true);
                cb7.setVisible(true);
                cb8.setVisible(false);
                cb9.setVisible(false);
                cb10.setVisible(false);
                break;
            case 7:
                cb1.setVisible(true);
                cb2.setVisible(true);
                cb3.setVisible(true);
                cb4.setVisible(true);
                cb5.setVisible(true);
                cb6.setVisible(true);
                cb7.setVisible(true);
                cb8.setVisible(true);
                cb9.setVisible(false);
                cb10.setVisible(false);
                break;
             case 8:
                cb1.setVisible(true);
                cb2.setVisible(true);
                cb3.setVisible(true);
                cb4.setVisible(true);
                cb5.setVisible(true);
                cb6.setVisible(true);
                cb7.setVisible(true);
                cb8.setVisible(true);
                cb9.setVisible(true);
                cb10.setVisible(false);
                break;
            case 9:
                cb1.setVisible(true);
                cb2.setVisible(true);
                cb3.setVisible(true);
                cb4.setVisible(true);
                cb5.setVisible(true);
                cb6.setVisible(true);
                cb7.setVisible(true);
                cb8.setVisible(true);
                cb9.setVisible(true);
                cb10.setVisible(true);
                break;
        }
        
    }//GEN-LAST:event_qtdeProfItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlocarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlocarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlocarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlocarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlocarProfessor(disciplinas,professores,instanciaDisc,instanciaProf).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnVoltarAloc;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb10;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JComboBox<String> cb3;
    private javax.swing.JComboBox<String> cb4;
    private javax.swing.JComboBox<String> cb5;
    private javax.swing.JComboBox<String> cb6;
    private javax.swing.JComboBox<String> cb7;
    private javax.swing.JComboBox<String> cb8;
    private javax.swing.JComboBox<String> cb9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> qtdeProf;
    // End of variables declaration//GEN-END:variables
}
