/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofinal.frontend;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import projetofinal.backend.Disciplina;
import projetofinal.backend.Professor;

/**
 *
 * @author rolemberg
 */
public class AlocarDisciplina extends javax.swing.JFrame {

    /**
     * Creates new form AlocarDisciplina
     */
    static List<String> horariosInst=new ArrayList<>();
    static List<Disciplina> disciplinas;
    static List<Professor> professores;
    
    static List<Disciplina>  instanciaDisc;
    static List<Professor> instanciaProf;
    
    static Disciplina discTemp;
    
    public AlocarDisciplina(List<Disciplina> discParam,List<Professor> profParam,List<Disciplina> discInst ,List<Professor> profInst) {
        initComponents();
        this.setVisible(true);
        
        disciplinas=discParam;
        professores=profParam;
        instanciaDisc=new ArrayList<Disciplina>();
        instanciaProf=profInst;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        checkH1Inst = new javax.swing.JCheckBox();
        checkH3Inst = new javax.swing.JCheckBox();
        checkHInst = new javax.swing.JCheckBox();
        checkH4Inst = new javax.swing.JCheckBox();
        checkH5Inst = new javax.swing.JCheckBox();
        checkH6Inst = new javax.swing.JCheckBox();
        checkH9Inst = new javax.swing.JCheckBox();
        checkH8Inst = new javax.swing.JCheckBox();
        checkH7Inst = new javax.swing.JCheckBox();
        checkH12Inst = new javax.swing.JCheckBox();
        checkH11Inst = new javax.swing.JCheckBox();
        checkH10Inst = new javax.swing.JCheckBox();
        checkH15Inst = new javax.swing.JCheckBox();
        checkH14Inst = new javax.swing.JCheckBox();
        checkH13Inst = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblDepto = new javax.swing.JLabel();
        lblCreditos = new javax.swing.JLabel();
        btnAddDiscInst = new javax.swing.JButton();
        btnVoltarDiscInst = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setText("Horário FIxo");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Segunda");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Terça");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Quarta");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Quinta");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Sexta");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("13:00-14:40");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("15:00-16:40");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("17:00-18:40");

        checkH1Inst.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkH1InstStateChanged(evt);
            }
        });
        checkH1Inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkH1InstActionPerformed(evt);
            }
        });

        checkH3Inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkH3InstActionPerformed(evt);
            }
        });

        checkHInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkHInstActionPerformed(evt);
            }
        });

        checkH4Inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkH4InstActionPerformed(evt);
            }
        });

        checkH5Inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkH5InstActionPerformed(evt);
            }
        });

        checkH6Inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkH6InstActionPerformed(evt);
            }
        });

        checkH9Inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkH9InstActionPerformed(evt);
            }
        });

        checkH8Inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkH8InstActionPerformed(evt);
            }
        });

        checkH7Inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkH7InstActionPerformed(evt);
            }
        });

        checkH12Inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkH12InstActionPerformed(evt);
            }
        });

        checkH11Inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkH11InstActionPerformed(evt);
            }
        });

        checkH10Inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkH10InstActionPerformed(evt);
            }
        });

        checkH15Inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkH15InstActionPerformed(evt);
            }
        });

        checkH14Inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkH14InstActionPerformed(evt);
            }
        });

        checkH13Inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkH13InstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkH1Inst)
                    .addComponent(checkH3Inst)
                    .addComponent(checkHInst))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(checkH4Inst)
                                    .addComponent(checkH5Inst)
                                    .addComponent(checkH6Inst))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(checkH9Inst)
                                    .addComponent(checkH8Inst)
                                    .addComponent(checkH7Inst))))))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkH11Inst)
                            .addComponent(checkH10Inst)
                            .addComponent(checkH12Inst))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkH15Inst)
                    .addComponent(jLabel9)
                    .addComponent(checkH14Inst)
                    .addComponent(checkH13Inst))
                .addGap(32, 32, 32))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6))
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkH1Inst)
                            .addComponent(jLabel10)
                            .addComponent(checkH4Inst)
                            .addComponent(checkH7Inst)
                            .addComponent(checkH10Inst))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(checkH5Inst)
                                    .addComponent(checkH8Inst)
                                    .addComponent(checkH11Inst)
                                    .addComponent(checkH14Inst))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(checkH3Inst)
                                    .addComponent(checkH6Inst)
                                    .addComponent(checkH9Inst)
                                    .addComponent(checkH12Inst)
                                    .addComponent(checkH15Inst)))
                            .addComponent(checkHInst)))
                    .addComponent(checkH13Inst))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setText("Codigo:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Alocar Disciplinas");

        btnBuscar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblNome.setText("Nome:");

        lblDepto.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblDepto.setText("Departamento:");

        lblCreditos.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblCreditos.setText("Creditos:");

        btnAddDiscInst.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAddDiscInst.setText("Adicionar");
        btnAddDiscInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDiscInstActionPerformed(evt);
            }
        });

        btnVoltarDiscInst.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVoltarDiscInst.setText("Voltar");
        btnVoltarDiscInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarDiscInstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddDiscInst)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscar))
                        .addComponent(lblNome)
                        .addComponent(lblDepto)
                        .addComponent(lblCreditos)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnVoltarDiscInst)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(lblNome)
                        .addGap(18, 18, 18)
                        .addComponent(lblDepto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCreditos)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnAddDiscInst, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltarDiscInst, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkH1InstStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkH1InstStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_checkH1InstStateChanged

    private void checkH1InstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkH1InstActionPerformed
        // TODO add your handling code here:

        if(checkH1Inst.isSelected()){
            horariosInst.add("h1");
            
        }else{
            
            horariosInst.remove("h1");
        }

    }//GEN-LAST:event_checkH1InstActionPerformed

    private void checkH3InstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkH3InstActionPerformed
        // TODO add your handling code here:

        if(checkH3Inst.isSelected()){
            horariosInst.add("h3");
            
        }else{
            
            horariosInst.remove("h3");
        }

    }//GEN-LAST:event_checkH3InstActionPerformed

    private void checkHInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHInstActionPerformed
        // TODO add your handling code here:
        if(checkHInst.isSelected()){
            horariosInst.add("h2");
            
        }else{
            
            horariosInst.remove("h2");
        }
    }//GEN-LAST:event_checkHInstActionPerformed

    private void checkH4InstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkH4InstActionPerformed
        // TODO add your handling code here:
        if(checkH4Inst.isSelected()){
            horariosInst.add("h4");
            
        }else{
            
            horariosInst.remove("h4");
        }
    }//GEN-LAST:event_checkH4InstActionPerformed

    private void checkH5InstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkH5InstActionPerformed
        // TODO add your handling code here:
        if(checkH5Inst.isSelected()){
            horariosInst.add("h5");
           
        }else{
            
            horariosInst.remove("h5");
        }
    }//GEN-LAST:event_checkH5InstActionPerformed

    private void checkH6InstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkH6InstActionPerformed
        // TODO add your handling code here:
        if(checkH6Inst.isSelected()){
            horariosInst.add("h6");
            
        }else{
            
            horariosInst.remove("h6");
        }
    }//GEN-LAST:event_checkH6InstActionPerformed

    private void checkH9InstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkH9InstActionPerformed
        // TODO add your handling code here:
        if(checkH9Inst.isSelected()){
            horariosInst.add("h9");
            
        }else{
            horariosInst.remove("h9");
            
        }
    }//GEN-LAST:event_checkH9InstActionPerformed

    private void checkH8InstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkH8InstActionPerformed
        // TODO add your handling code here:
        if(checkH8Inst.isSelected()){
            horariosInst.add("h8");
            
        }else{
            horariosInst.remove("h8");
            
        }
    }//GEN-LAST:event_checkH8InstActionPerformed

    private void checkH7InstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkH7InstActionPerformed
        // TODO add your handling code here:
        if(checkH7Inst.isSelected()){
            horariosInst.add("h7");
            
        }else{
            horariosInst.remove("h7");
            
        }
    }//GEN-LAST:event_checkH7InstActionPerformed

    private void checkH12InstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkH12InstActionPerformed
        // TODO add your handling code here:
        if(checkH12Inst.isSelected()){
            horariosInst.add("h12");
            
        }else{
            horariosInst.remove("h12");
            
        }
    }//GEN-LAST:event_checkH12InstActionPerformed

    private void checkH11InstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkH11InstActionPerformed
        // TODO add your handling code here:
        if(checkH11Inst.isSelected()){
            horariosInst.add("h11");
            
        }else{
            horariosInst.remove("h11");
            
        }
    }//GEN-LAST:event_checkH11InstActionPerformed

    private void checkH10InstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkH10InstActionPerformed
        // TODO add your handling code here:
        if(checkH10Inst.isSelected()){
            horariosInst.add("h10");
            
        }else{
            horariosInst.remove("h10");
            
        }
    }//GEN-LAST:event_checkH10InstActionPerformed

    private void checkH15InstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkH15InstActionPerformed
        // TODO add your handling code here:
        if(checkH15Inst.isSelected()){
            horariosInst.add("h15");
            
        }else{
            horariosInst.remove("h15");
            
        }
    }//GEN-LAST:event_checkH15InstActionPerformed

    private void checkH14InstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkH14InstActionPerformed
        // TODO add your handling code here:
        if(checkH14Inst.isSelected()){
            horariosInst.add("h14");
            
        }else{
            horariosInst.remove("h14");
            
        }
    }//GEN-LAST:event_checkH14InstActionPerformed

    private void checkH13InstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkH13InstActionPerformed
        // TODO add your handling code here:
        if(checkH13Inst.isSelected()){
            horariosInst.add("h13");
            
        }else{
            horariosInst.remove("h13");
            
        }
    }//GEN-LAST:event_checkH13InstActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String textTemp=textCodigo.getText();
        boolean existe=false;
        if(textTemp.equals("")){
            JOptionPane.showMessageDialog( null , " Campo codigo nulo" , " Erro!" , JOptionPane.WARNING_MESSAGE );
        }else{
            int n=disciplinas.size();
            for (int i = 0; i < n; i++) {
                
                if(textTemp.equalsIgnoreCase(disciplinas.get(i).getCodigo())){
                    discTemp=disciplinas.get(i);
                    lblNome.setText("Nome:"+disciplinas.get(i).getNome());
                    lblDepto.setText("Departamento:"+disciplinas.get(i).getDepartamento());
                    lblCreditos.setText("Creditos:"+disciplinas.get(i).getCreditos());
                    existe=true;
                    break;
                }
                
            }
            if(existe==false){
                JOptionPane.showMessageDialog( null , " Disciplina nao encontrada" , " Erro!" , JOptionPane.WARNING_MESSAGE );
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAddDiscInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDiscInstActionPerformed
        // TODO add your handling code here:
        String textTemp=textCodigo.getText();
        if(textTemp.equals(""))
            JOptionPane.showMessageDialog( null , " Campo codigo nulo" , " Erro!" , JOptionPane.WARNING_MESSAGE );
        
        if(horariosInst.size()*2>discTemp.getCreditos()){
            JOptionPane.showMessageDialog( null , " Horario pre-definido maior que carga horaria" , " Erro!" , JOptionPane.WARNING_MESSAGE );
        }else{
             discTemp.setRestricaoHorario(horariosInst);
             instanciaDisc.add(discTemp);
             JOptionPane.showMessageDialog( null , " Disciplina adicionada" , " Adicionada" , JOptionPane.INFORMATION_MESSAGE );
             
        }
    }//GEN-LAST:event_btnAddDiscInstActionPerformed

    private void btnVoltarDiscInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarDiscInstActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new InstanciarProblema(disciplinas,professores,instanciaDisc,instanciaProf).setLocationRelativeTo(null);
    }//GEN-LAST:event_btnVoltarDiscInstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlocarDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlocarDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlocarDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlocarDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlocarDisciplina(disciplinas,professores,instanciaDisc,instanciaProf).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDiscInst;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnVoltarDiscInst;
    private javax.swing.JCheckBox checkH10Inst;
    private javax.swing.JCheckBox checkH11Inst;
    private javax.swing.JCheckBox checkH12Inst;
    private javax.swing.JCheckBox checkH13Inst;
    private javax.swing.JCheckBox checkH14Inst;
    private javax.swing.JCheckBox checkH15Inst;
    private javax.swing.JCheckBox checkH1Inst;
    private javax.swing.JCheckBox checkH3Inst;
    private javax.swing.JCheckBox checkH4Inst;
    private javax.swing.JCheckBox checkH5Inst;
    private javax.swing.JCheckBox checkH6Inst;
    private javax.swing.JCheckBox checkH7Inst;
    private javax.swing.JCheckBox checkH8Inst;
    private javax.swing.JCheckBox checkH9Inst;
    private javax.swing.JCheckBox checkHInst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCreditos;
    private javax.swing.JLabel lblDepto;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField textCodigo;
    // End of variables declaration//GEN-END:variables
}
