/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofinal.frontend;

import java.util.List;
import javax.swing.DefaultListModel;
import projetofinal.backend.Disciplina;
import projetofinal.backend.Professor;

/**
 *
 * @author rolemberg
 */
public class Resultado extends javax.swing.JFrame {

    /**
     * Creates new form Resultado
     */
    
    static List<Disciplina> disciplinas;
    static List<Professor> professores;
    
    static List<Disciplina>  instanciaDisc;
    static List<Professor> instanciaProf;
    
    static String[]resultadoAlocacao;
    static List<String> profsNaoAlocados;
    static List<String> materiasNaoAlocadas;
    
    public Resultado(List<Disciplina> discParam,List<Professor> profParam,List<Disciplina> discInst ,List<Professor> profInst,String[] resultParam,List<String> profNotParam,List<String> matNotParam) {
        initComponents();
        this.setVisible(true);
        disciplinas=discParam;
        professores=profParam;
        instanciaDisc=discInst;
        instanciaProf=profInst;
        resultadoAlocacao=resultParam;
        profsNaoAlocados=profNotParam;
        materiasNaoAlocadas=matNotParam;
        
        
        
        //Segunda 
        tabela.setValueAt(resultadoAlocacao[0], 0, 1);
        tabela.setValueAt(resultadoAlocacao[1], 1, 1);
        tabela.setValueAt(resultadoAlocacao[2], 2, 1);
        
        //Terca
        tabela.setValueAt(resultadoAlocacao[3], 0, 2);
        tabela.setValueAt(resultadoAlocacao[4], 1, 2);
        tabela.setValueAt(resultadoAlocacao[5], 2, 2);
        
        //Quarta
        tabela.setValueAt(resultadoAlocacao[6], 0, 3);
        tabela.setValueAt(resultadoAlocacao[7], 1, 3);
        tabela.setValueAt(resultadoAlocacao[8], 2, 3);
        
        //Quinta
        tabela.setValueAt(resultadoAlocacao[9], 0, 4);
        tabela.setValueAt(resultadoAlocacao[10], 1, 4);
        tabela.setValueAt(resultadoAlocacao[11], 2, 4);
        
        //Sexta
        tabela.setValueAt(resultadoAlocacao[12], 0, 5);
        tabela.setValueAt(resultadoAlocacao[13], 1, 5);
        tabela.setValueAt(resultadoAlocacao[14], 2, 5);
        
        listProfNot.removeAll();
        listMatNot.removeAll();
        
        
        DefaultListModel modelDiscNot = new DefaultListModel();
        if(materiasNaoAlocadas!=null){
            int n = materiasNaoAlocadas.size();
            for (int i=0; i<n; i++) {
            
            modelDiscNot.addElement("Nome: "+ materiasNaoAlocadas.get(i));
            modelDiscNot.addElement("******************************************************************");
            
            }
            listMatNot.setModel(modelDiscNot);
        
        }
        
        DefaultListModel modelProfNot = new DefaultListModel();
        if(profsNaoAlocados!=null){
            int n = profsNaoAlocados.size();
            
            for (int i=0; i<n; i++) {

                
                modelProfNot.addElement("Nome:"+profsNaoAlocados.get(i));
               
            
                modelProfNot.addElement("***************************************************************");  
            }
            listProfNot.setModel(modelProfNot);
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listProfNot = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listMatNot = new javax.swing.JList<>();
        btnVoltarResult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"13:00-15:00", null, null, null, null, null},
                {"15-00:17:00", null, null, null, null, null},
                {"17:00-19:00", null, null, null, null, null}
            },
            new String [] {
                "HORARIOS", "SEGUNDA", "TERCA", "QUARTA", "QUINTA", "SEXTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setRowHeight(80);
        jScrollPane1.setViewportView(tabela);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Resultado");

        jScrollPane3.setViewportView(listProfNot);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Professores nao alocados");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Disciplinas nao alocadas");

        jScrollPane4.setViewportView(listMatNot);

        btnVoltarResult.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVoltarResult.setText("Voltar");
        btnVoltarResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(86, 86, 86))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addComponent(btnVoltarResult, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVoltarResult)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarResultActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new InstanciarProblema(disciplinas,professores,instanciaDisc,instanciaProf).setLocationRelativeTo(null);
    }//GEN-LAST:event_btnVoltarResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultado(disciplinas,professores,instanciaDisc,instanciaProf,resultadoAlocacao,profsNaoAlocados,materiasNaoAlocadas).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltarResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listMatNot;
    private javax.swing.JList<String> listProfNot;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
